export const PROCESSING_STATES = {
  INIT: 'INIT',
  INVALID_FILE: 'INVALID_FILE',
  PREPARING_IMAGE: 'PREPARING_IMAGE',
  SIMULATING_PRINT: 'SIMULATING_PRINT',
  GENERATING_PDF: 'GENERATING_PDF',
  DONE: 'DONE'
};
